### PR TITLE
Improve HeppyComponent filtering and handling for dodgy root files

### PR DESCRIPTION
**Pull request by benkrikler**
Whilst integrating the RA1 sequence, I found two issues that I thought were best tackled by adapting alphatwirl:
 * Improve method to exclude directories of a heppy component
 * Be more careful when trying to handle bad root files when we split up the datasets.

### CODE REVIEW

**Comment by benkrikler** [comment]
Hmm, weird, the current test is failing for Python 3, but it's not in any obvious syntax issue, and really seems to be coming from a method that's implemented differently in the different python versions. Not sure what's the issue (Python 2 runs all tests fine...) at this point

**Comment by TaiSakuma** [comment]
@benkrikler, are you actually requesting a pull? your original PR message indicates that you are not.

**Comment by benkrikler** [comment]
Yes, I'd like to merge this in if possible.  I've updated the description.

**Comment by TaiSakuma** [comment]
Ok. A lot going on in this PR. This PR contains at least 3 different changes - in WorkinArea, HeppyResult, and, DatasetIntoEventBuildersSplitter. Can you make one PR for each?

Then we can discuss and merge separately. If all in the same PR, it won't be merged until all issues are resolved.

**Pull request closed without merging**
